name: logger_flutter_ns
description: A simple plug & play flutter logger console. You can use this plugin for logging on ide or by shaking your phone to see logs on phone.
version: 0.0.8
homepage: https://github.com/ahmetcj4/logger_flutter_ns/

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.0
  logger: ^1.1.0
  path_provider: ^2.0.11
  share_plus: ^6.2.0
  sensors_plus: ^2.0.1
dev_dependencies:
  test: ^1.3.0