name: logger_flutter_ns
description: A simple plug & play flutter logger console.
version: 0.0.1
homepage: https://github.com/ahmetcj4/logger_flutter_ns/
documentation: https://github.com/ahmetcj4/logger_flutter_ns/README.md

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  logger: ^1.0.0
  path_provider: ^2.0.2
  share_plus: ^2.1.4
  sensors_plus: ^1.0.2
dev_dependencies:
  test: ^1.3.0
